### ISSUE TITLE
Adminstration -> News

### ISSUE THREAD

**Issue by Zulsaframano** [HikeGame/2moons-2.0#1]
Wenn man in der Adminstrationszentrale die News wählt kommt folgende Fehlermeldung:
 
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /includes/pages/adm/ShowNewsPage.php on line 69

**Comment by HikeGame** [comment]
Corrected 4f9659a2ec48d00be644e83a791a090feb905ba0
