### ISSUE TITLE
MissionCaseAttack, MissionCaseDestruction Debris update increase

### ISSUE THREAD

**Issue by byazrail** [HikeGame/2moons-2.0#12]
Hi,
Reference bug on forum;
https://2moons.de/index.php?thread/750-debris-bug/

**Comment by byazrail** [comment]
MissionCaseAttack.
moon attack type debris field not possible merge type.
https://github.com/HikeGame/2moons-2.0/blob/master/includes/classes/missions/MissionCaseAttack.class.php#L330
330 lines.
`if($this->_fleet['fleet_end_type'] == 3)
{
// Use planet debris, if attack on moons
$sql= "SELECT der_metal, der_crystal FROM %%PLANETS%% WHERE id_luna = :moonId;";
$targetDebris= $db->selectSingle($sql, array(
':moonId' => $this->_fleet['fleet_end_id']
));
$targetPlanet['der_metal']= $targetDebris['der_metal'];
$targetPlanet['der_crystal'] = $targetDebris['der_crystal'];
}`

**Comment by HikeGame** [comment]
The code via the issue is not correct because it will multiply the debris

**Comment by byazrail** [comment]
MissionCaseDestruction
https://github.com/HikeGame/2moons-2.0/blob/master/includes/classes/missions/MissionCaseDestruction.class.php#L322
332 lines.
`if($this->_fleet['fleet_end_type'] == 3)
{
// Use planet debris, if attack on moons
$sql= "SELECT der_metal, der_crystal FROM %%PLANETS%% WHERE id_luna = :moonId;";
$targetDebris= $db->selectSingle($sql, array(
':moonId' => $this->_fleet['fleet_end_id']
));
$targetPlanet['der_metal']= $targetDebris['der_metal'];
$targetPlanet['der_crystal'] = $targetDebris['der_crystal'];
}`

**Comment by byazrail** [comment]
Not multiply removed first comment.

**Comment by HikeGame** [comment]
commit ok https://github.com/HikeGame/2moons-2.0/commit/5d15d3f28309b130891a92f3a8c5f6a7e1f8c713
