### ISSUE TITLE
Wrong parameter?

### ISSUE THREAD

**Issue by lukacavic** [HikeGame/2moons-2.0#15]
Passing id_planet for user id? Is this correct?

https://github.com/HikeGame/2moons-2.0/blob/7a52e95c0f9147207a9c486ecddc287a8171b6a9/includes/pages/game/ShowAlliancePage.class.php#L202

**Comment by HikeGame** [comment]
Is not correct thanks

**Comment by HikeGame** [comment]
Fix
https://github.com/HikeGame/2moons-2.0/commit/33104a8686f736c444262e04c8b55298fff86967
