### ISSUE TITLE
fixed hold position

### ISSUE THREAD

**Issue by yamilrh** [HikeGame/2moons-2.0#17]
https://github.com/HikeGame/2moons-2.0/blob/2985ae79584130f7dd13d29ee5d2a341bdb0c440/includes/classes/class.FleetFunctions.php#L345
Change for
`if($fleetResult['fleet_mission'] == 5 && $fleetResult['fleet_mess'] == FLEET_HOLD) {`

la misión de mantener posición cuando le das volver esta tomando el tiempo de regreso y no lo que consumió solo de ida.

**Comment by HikeGame** [comment]
thanks Fix addon
https://github.com/HikeGame/2moons-2.0/commit/2c8d7b5d1a80e0afd2efc150f63850df5ab5e453
