### ISSUE TITLE
Fatal error: Uncaught ErrorException

### ISSUE THREAD

**Issue by Derodin** [HikeGame/2moons-2.0#18]
After LogIn:

`Fatal error: Uncaught ErrorException: Undefined offset: 8192 in E:\xampp\htdocs\one\includes\GeneralFunctions.php:506
Stack trace:
#0 E:\xampp\htdocs\one\includes\GeneralFunctions.php(506): errorHandler(8, 'Undefined offse...', 'E:\\xampp\\htdocs...', 506, Array)
#1 [internal function]: exceptionHandler(Object(ErrorException))
#2 {main} thrown in E:\xampp\htdocs\one\includes\GeneralFunctions.php on line 506`

how can i fix this?

**Comment by yamilrh** [comment]
cual es la linea 506?

**Comment by Chewbaka69** [comment]
You need to add line after that:
https://github.com/HikeGame/2moons-2.0/blob/master/includes/GeneralFunctions.php#L472
add this:
ligne 472 at the end of the line add `,`
after ligne 472 add: `E_DEPRECATED 	=> 'DEPRECATED ERROR'`

and that works :)

**Comment by HikeGame** [comment]
Fix addon https://github.com/HikeGame/2moons-2.0/commit/6529b296b1d124fa6cdcc96a0bfce0b070691f23

**Comment by HikeGame** [comment]
https://github.com/HikeGame/2moons-2.0/commit/6529b296b1d124fa6cdcc96a0bfce0b070691f23
