### ISSUE TITLE
Fresh Install - Error 500

### ISSUE THREAD

**Issue by Juge-Gabranth-15** [HikeGame/2moons-2.0#5]
Hi @HikeGame ,

Make a fresh install, just copy/paste config.sample.php and rename it config.php and then I'm redirect to

`install/index.php?mode=upgrade`

And error 500 here too.

Any idea of why ? That's pure fresh install.

**Comment by HikeGame** [comment]
https://www.youtube.com/watch?v=QL9-IwjQIXw&list=PLrQgmYG25sGBW1OKDwh-u07wqlojQl-xS

**Comment by Juge-Gabranth-15** [comment]
My bad, sorry for that, but can still useful for other person:

Error caused by CPanel

`[Thu Mar 01 15:47:10.265656 2018] [:error] [pid 2440] [client xxx.xxx.xxx.xxx:xxxxx] SoftException in Application.cpp:657: Directory "/home/install" is writeable by group`

Need to put folder to 755 and php file from 664 to 644 permissions.
